### ISSUE TITLE
Tsoha vertaisarvionti

### ISSUE THREAD

**Issue by elonheimo** [sofiak-hel/filmflask#1]
Funktiot ja tiedostot ovat jaoteltu selkeästi. README.md tiedosto on informatiivinen. Commitit hyviä. Github repositorio on siisti. Sql Schemassa tykkäsin erityisesti, miten roolit on jaettu tietokannassa.

Huomioita:
- Jos käyttäjä jättää kommentin, niin sivu päivittyy ja video alkaa alusta.
- 5.6 MB tiedostolla "Request Entity Too Large"- kenties "peruskäyttäjälle" informatiivisempi error sivu
- käyttäjille voisi lisätä default avatarin
- Käyttäjän olisi hyvä pystyä poistamaan julkaisemansa video
- adminin password hash githubissa, sinänsä pieni riski, mutta riski kuitenkin

Projekti on jo nyt varsin laaja ja toimiva. 
Olin aivan ällikällä lyöty, kun avasin sivun herokussa. Loistavaa työtä!

**Comment by sofiak-hel** [comment]
Kiitos paljon palautteesta ja erityiesesti kehuista! Olenkin melko ylpeä tähän projektiin, vaikka normaalisti kirjoitankin Rust:illa, enkä oikein pidä Pythonista. Haluaisin vastata kuitenkin näihin huomioihin yksi kerrallaan;



- Jos käyttäjä jättää kommentin, niin sivu päivittyy ja video alkaa alusta.
5.6 MB tiedostolla "Request Entity Too Large"- kenties "peruskäyttäjälle" informatiivisempi error sivu
> Jep, tämä on tiedossa. Valitettavasti kyseinen virheilmoitus johtuu Flaskin omasta toiminnasta ja en ole ihan varma voiko sitä muuttaa. Se mitä aion kuitenkin asialle tehdä on lisätä front-endiin javascriptiä joka estää yli 5MB tiedostojen lataamisen (tai 200KB kuvien tapauksessa)
- käyttäjille voisi lisätä default avatarin
> Kiitos tästä huomiosta! Unohdin sen kokonaan. Tämä oli kyllä tarkoitus lisätä alunperin, mutta se unohtui enkä keksinyt sille riittävän nopeasti hyvää ratkaisua tätä palautusta varten.
- Käyttäjän olisi hyvä pystyä poistamaan julkaisemansa video
> Tämä olikin listattu README:ssa ominaisuuksina jota aion lisätä seuraavalla viikolla :)
- adminin password hash githubissa, sinänsä pieni riski, mutta riski kuitenkin
> Jep, hyvä huomio, tosin kyseinen admin-tunnus on itse herokulla poistettu, joten riskiä ei varsinaisesti ole. Minulla oli kyllä tarkoitus lisätä itse koodiinkin konfiguraatiosta riippuva admin-tilin automaattinen poisto, mutta en sillekkään keksinyt sopivaa ratkaisua palautukseen mennessä.
